### ISSUE TITLE
Valet install command says that PHP is not installed

### ISSUE THREAD

**Issue by sergiienko** [jmarcher/valet-linux#23]
Could anyone point out what's wrong with my system?

> valet install
> [php7.0] is not installed, installing it now via Ubuntu... 🍻
> 1  
>   [DomainException]  
>   Ubuntu was unable to install [php7.0].  
> install

While PHP is actually installed:

> php -v
> PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.8-0ubuntu0.16.04.2, Copyright (c) 1999-2016, by Zend Technologies

**Comment by thelowtech** [comment]
I am having the same issue followed the docs exactly and cannot get it to move past this point

**Comment by jmarcher** [comment]
I noticed I need a different config for each distro, will do this but I do not have time at the time, flying back home next week

**Comment by ceesco53** [comment]
@jmarcher This brings up something I've been thinking:

Add command line install override parameters.  An example valet install with command line overrides:

`valet install --fpm-config=/etc/fpm/php-fpm.conf  --php-bin=/usr/local/bin/php --fpm-service=php-fpm`

I could probably code that for you for all the config variables in config.php.  As an Arch user, this would make me happy.   I don't think overrides would need to be used except for the valet install command.  Ultimately this would fix the OP's issue, maybe even create a .valet/env file to store overrides for re-installs.

**Comment by robmilward** [comment]
+1
Same for me on Linux Mint

A hacky fix to get through the install, assuming you _are_ running php7.0-fpm:
Add `if ($package === 'php') return true;` to the top of `installed()` in `valet-linux/cli/Valet/Ubuntu.php`

The rest of the install went fine, and it works without a problem

**Comment by remailednet** [comment]
I had the same issue running Linux Mint 18. PHP 7.0 was installed but not the php7.0-fpm package. Once I installed that valet install went just fine.

It looks like there needs to be some tweaking done on the install process.

**Comment by jmarcher** [comment]
Which version of valet are you using?
I'm sorry about that i'm a Manjaro User so for Ubuntu I rely on the users for testing things out
