### ISSUE TITLE
Valet link - problem with permissions

### ISSUE THREAD

**Issue by marcinjagielnicki** [jmarcher/valet-linux#27]
When i'm linking directory to valet it's linked in wrong permissions i think. 

marcin@marcin-Inspiron-7720:~/.config$ valet links
drwxr-xr-x 2 marcin root   4096 wrz 29 23:59 .
drwxr-xr-x 6 marcin root   4096 wrz 29 21:48 ..
lrwxrwxrwx 1 marcin marcin   28 wrz 29 23:59 Project -> /home/marcin/Projects/Project

Valet also runs with root permissions. 

When i'm trying to open Project url i'm getting 404 - Not Found

**Comment by adriaanzon** [comment]
Valet should actually only use sudo when the command requires it: https://github.com/jmarcher/valet-linux/blob/81349b9bf49e2ef57f636b879abd4cf3a914b770/valet#L23-L30

Valet-ubuntu already does this. I'm curious to know why this fork of valet requires sudo for every command.

**Comment by marcinjagielnicki** [comment]
I resolved this problem already. Directory name should be lowercased because valet is searching for lowercased directories. 
https://github.com/jmarcher/valet-linux/blob/81349b9bf49e2ef57f636b879abd4cf3a914b770/server.php#L46-L52
