### ISSUE TITLE
Valet under latest Manjaro

### ISSUE THREAD

**Issue by mikield** [jmarcher/valet-linux#28]
I don't know why, but I had problems when installing valet.

My `php-fpm` path was without version.
My `php-fpm` path is `/etc/php/php-fpm.d/www.conf`.
#### Why I have created this issue?

Cause I even did not know about config.php file in the project, where I have changed the path.
I think there should be some info in Readme.md about this file.

Sorry for my bad English.

**Comment by mikield** [comment]
And... should it be not 127.0.0.1?
![_2016-10-24_23-03-34](https://cloud.githubusercontent.com/assets/4073672/19663848/2304e168-9a3e-11e6-826f-71b1317d8eff.png)

**Comment by adriaanzon** [comment]
It should at least be in the readme indeed. It would be better to provide a different config for each distro, as mentioned here https://github.com/jmarcher/valet-linux/issues/23#issuecomment-241934448

**Comment by adriaanzon** [comment]
See https://github.com/jmarcher/valet-linux/issues/3 for the 127.0.53.53 thing.
What I ended up doing was the following:

Comment out this line in `/etc/NetworkManager/NetworkManager.conf`:

```
dns=default
```

Uncomment this line in `/etc/resolvconf.conf`

```
#name_servers=127.0.0.1
```

Append this to `/etc/dnsmasq.conf`

```
no-resolv
server=8.8.8.8
server=8.8.4.4
```

**Comment by mikield** [comment]
@adriaanzon, hmm... I have done how you said, and even re-entered system.
But when I am pinging some.dev i get the same 127.0.53.53.

Seems whole pakadge is buggy under Manjaro (or Arch).
Cause when I want to change domain in tryies to put some content to `Caddy` file in `~/.valet/` folder. But `Caddy` is folder :sweat_smile:

**Comment by mikield** [comment]
@adriaanzon, ok got it working :slightly_smiling_face: 
I had to edit `etc/resolv.conf` and set `namespace 127.0.0.1`. Then I have updated to `1.2.10` and run

```
valet uninstal
rm -rf ~/.valet/
valet install
```

**Comment by jmarcher** [comment]
I just uploaded a new version with separated configuration for each distribution, you may need to update your composer global composer.json in order to accept the 2.0 tagged version.

Hope it solves the problems for all of you guys

And also hopping to see new distributions, I don't use other than Manjaro so I can not test this in another distribution

**Comment by adriaanzon** [comment]
Thanks, it works without editing the config.php now :smile:

**Comment by jmarcher** [comment]
Glad to hear
