### ISSUE TITLE
Valet - Not Found 404

### ISSUE THREAD

**Issue by ajdemoed** [jmarcher/valet-linux#33]
Hello there. I am trying to get valet working on my Ubuntu laptop. Everything seems to be installed correctly. I can ping laravel.dev and get a response. I have setup all directory permissions for bootstrap and storage folders. When I open up in the browser I get a 404 - Not Found error. It seems like Valet cannot find the laravel folder. 

Any ideas how to solve this?

**Comment by jmarcher** [comment]
Hi, did you parked a folder or tried to link a single project to valet.

Do you have any output from the valet console or logs?

Am 18.11.2016 15:30 schrieb "ajdemoed" notifications@github.com:

**Comment by ajdemoed** [comment]
Ok I am one step further.. I have changed the permissions on the Code directory where my projects live. Now I get a "Apache2 Ubuntu Default Page: It Works" ... No matter what *.dev url I use I am still getting directed to this page. I have used "valet park" on the Code directory and "valet link" on the project directory. 

Thanks for your help !

**Comment by ajdemoed** [comment]
**This is from "valet status -vvv" :** 

● caddy.service - Caddy webserver
   Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: active (running) since za 2016-11-19 10:08:18 CET; 1min 45s ago
     Docs: https://caddyserver.com/
 Main PID: 8234 (caddy)
    Tasks: 11 (limit: 4915)
   CGroup: /system.slice/caddy.service
           └─8234 /home/ajdemoed/.composer/vendor/jmarcher/valet-linux/bin/caddy --conf=/home/ajdemoed/.valet/Caddyfile -pidfile=/var/run/caddy.pid

nov 19 10:08:18 arjan systemd[1]: Started Caddy webserver.
nov 19 10:08:18 arjan caddy[8234]: Activating privacy features... done.
nov 19 10:08:18 arjan caddy[8234]: :80

● php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.0-fpm.service; enabled; vendor preset: enabled)
   Active: active (running) since za 2016-11-19 10:08:16 CET; 1min 47s ago
     Docs: man:php-fpm7.0(8)
 Main PID: 8177 (php-fpm7.0)
   Status: "Processes active: 0, idle: 2, Requests: 7, slow: 0, Traffic: 0req/sec"
    Tasks: 3 (limit: 4915)
   CGroup: /system.slice/php7.0-fpm.service
           ├─8177 php-fpm: master process (/etc/php/7.0/fpm/php-fpm.conf)
           ├─8178 php-fpm: pool www
           └─8179 php-fpm: pool www

nov 19 10:08:16 arjan systemd[1]: Starting The PHP 7.0 FastCGI Process Manager...
nov 19 10:08:16 arjan systemd[1]: Started The PHP 7.0 FastCGI Process Manager.

**This is my output for "valet links -vvv" :** 

total 8
drwxr-xr-x 2 ajdemoed root 4096 nov 19 10:08 .
drwxr-xr-x 7 ajdemoed root 4096 nov 19 10:11 ..
lrwxrwxrwx 1 root     root   27 nov 19 10:08 laravel -> /home/ajdemoed/Code/laravel
lrwxrwxrwx 1 root     root   34 nov 18 22:16 public -> /home/ajdemoed/Code/laravel/public

**And "valet paths -vvv" :** 

[
    "/home/ajdemoed/.valet/Sites",
    "/home/ajdemoed/Code",
    "/home/ajdemoed/Code/laravel"
]

**Comment by jmarcher** [comment]
Oh I see, Apache and Caddy are in conflict, you need to disable the Apache service and let Caddy do the work

**Comment by ajdemoed** [comment]
I really dont get it... I have completely removed apache2 service. When I do the command "sudo service apache2 start" I get: "Failed to start apache2.service: Unit apache2.service not found." It seems like apache2 cannot conflict with Caddy anymore. I still get the Valet - Not Found 404 error .... Please advise me on how to fix this. Thanks for the patience :)

**Comment by jmarcher** [comment]
The service is called httpd, try with
`sudo systemctl disable httpd`
`sudo systemctl stop httpd`

**Comment by ajdemoed** [comment]
**sudo systemctl disable httpd**: 

Failed to disable unit: No such file or directory

**dpkg -l | httpd**:

No command 'httpd' found, did you mean:
 Command 'http' from package 'httpie' (universe)
 Command 'xttpd' from package 'xtide' (universe)
httpd: command not found

It seems like httpd is not installed on my system...

**Comment by jmarcher** [comment]
Try 
sudo systemctl stop apache2.service

somehow you have Apache running on your computer

**Comment by ajdemoed** [comment]
**sudo systemctl stop apache2.service**

Failed to stop apache2.service: Unit apache2.service not loaded.

**dpkg -l | apache2**

The program 'apache2' is currently not installed. You can install it by typing:
sudo apt install apache2-bin

Is it possible that Valet is looking at the wrong location for my sites? No matter what url I use with .dev at the end all will result in 404 - Not Found.

**Comment by jmarcher** [comment]
Can you check inside the .valet folder if your project folder is really parked?

in:
/home/{your_username}/.valet/config.json

**Comment by ajdemoed** [comment]
{
    "domain": "dev",
    "paths": [
        "/home/ajdemoed/.valet/Sites",
        "/home/ajdemoed/Code",
        "/home/ajdemoed/Code/laravel"
    ]
}

**Comment by jmarcher** [comment]
`{
"domain": "dev",
"paths": [
"/home/ajdemoed/Code"
]
}`

Assuming that is the folder where your projects are, try to restart valet and try again

using 
`valet restart`

**Comment by ajdemoed** [comment]
Still 404...
Could it be a permission problem?

**Comment by jmarcher** [comment]
I'm clueless now, really.

what does valet status outputs? the same as on the top?

**Comment by ajdemoed** [comment]
**valet status -vvv**

● caddy.service - Caddy webserver
   Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: active (running) since zo 2016-11-20 15:09:09 CET; 3h 15min ago
     Docs: https://caddyserver.com/
 Main PID: 3987 (caddy)
   CGroup: /system.slice/caddy.service
           └─3987 /home/ajdemoed/.composer/vendor/jmarcher/valet-linux/bin/caddy --conf=/home/ajdemoed/.valet/Caddyfile -pidfile=/var/run/caddy.pid

nov 20 15:09:09 arjan systemd[1]: Started Caddy webserver.
nov 20 15:09:09 arjan caddy[3987]: Activating privacy features... done.
nov 20 15:09:09 arjan caddy[3987]: code.dev:80
nov 20 15:09:09 arjan caddy[3987]: :80
nov 20 15:09:09 arjan caddy[3987]: code.dev:443

● php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.0-fpm.service; enabled; vendor preset: enabled)
   Active: active (running) since zo 2016-11-20 15:09:07 CET; 3h 15min ago
     Docs: man:php-fpm7.0(8)
 Main PID: 3921 (php-fpm7.0)
   Status: "Processes active: 0, idle: 2, Requests: 4, slow: 0, Traffic: 0req/sec"
   CGroup: /system.slice/php7.0-fpm.service
           ├─3921 php-fpm: master process (/etc/php/7.0/fpm/php-fpm.conf)
           ├─3928 php-fpm: pool www
           └─3929 php-fpm: pool www

nov 20 15:09:07 arjan systemd[1]: Starting The PHP 7.0 FastCGI Process Manager...
nov 20 15:09:07 arjan systemd[1]: Started The PHP 7.0 FastCGI Process Manager.

**valet links -vvv**

total 8
drwxr-xrwx 2 ajdemoed root 4096 nov 19 10:08 .
drwxr-xr-x 7 ajdemoed root 4096 nov 20 15:06 ..
lrwxrwxrwx 1 root     root   27 nov 19 10:08 laravel -> /home/ajdemoed/Code/laravel
lrwxrwxrwx 1 root     root   34 nov 18 22:16 public -> /home/ajdemoed/Code/laravel/public

**Comment by ajdemoed** [comment]
Where is the server pointing to? ~/.valet/Sites ?? Do I need to name my folder also Sites?

Do I need to do port forwarding maybe?

How can I check Caddy is working? When I do "dpkg -l | caddy.service" I get : 

caddy.service: command not found

Also with "dpkg -l | caddy".

**Comment by jmarcher** [comment]
What is inside /home/ajdemoed/Code ?

What is the name of the problem you are trying to enter?

**Comment by ajdemoed** [comment]
It's a laravel project named "laravel".

**Comment by jmarcher** [comment]
Try installing version 2.1.0 and tell me if this solves your problem

**Comment by ajdemoed** [comment]
**valet -V**

Laravel Valet (Linux Edition) version 2.1.0

**valet status**

● caddy.service - Caddy webserver
   Loaded: loaded (/lib/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: active (running) since do 2016-11-24 23:03:08 CET; 3min 15s ago
     Docs: https://caddyserver.com/
 Main PID: 6142 (caddy)
   CGroup: /system.slice/caddy.service
           └─6142 /home/ajdemoed/.composer/vendor/jmarcher/valet-linux/bin/caddy --conf=/home/ajdemoed/.valet/Caddyfile -pidfile=/var/run/caddy.pid

nov 24 23:03:08 arjan-demoed systemd[1]: Started Caddy webserver.
nov 24 23:03:08 arjan-demoed caddy[6142]: Activating privacy features... done.
nov 24 23:03:08 arjan-demoed caddy[6142]: :80

● php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.0-fpm.service; enabled; vendor preset: enabled)
   Active: active (running) since do 2016-11-24 23:03:05 CET; 3min 18s ago
 Main PID: 6111 (php-fpm7.0)
   Status: "Processes active: 0, idle: 2, Requests: 2, slow: 0, Traffic: 0req/sec"
   CGroup: /system.slice/php7.0-fpm.service
           ├─6111 php-fpm: master process (/etc/php/7.0/fpm/php-fpm.conf)                      
           ├─6114 php-fpm: pool www                                                            
           └─6115 php-fpm: pool www                                                            

nov 24 23:03:05 arjan-demoed systemd[1]: Starting The PHP 7.0 FastCGI Process Manager...
nov 24 23:03:05 arjan-demoed systemd[1]: Started The PHP 7.0 FastCGI Process Manager.

**Still 404 Not Found :(
I think I will move to Apache Xampp stack. Thanks a lot for your help!**
