### ISSUE TITLE
valet installation folder

### ISSUE THREAD

**Issue by cargie** [jmarcher/valet-linux#4]
seems like my home directory points to '/root' on $_SERVER['HOME']

**Comment by cargie** [comment]
What's the point of this code? because this is the reason why my valet folder installation points to root.
 `define('VALET_HOME_PATH', $_SERVER['HOME'] . '/.valet');`

**Comment by jmarcher** [comment]
This is because some commands require root access in order to run

**Comment by cargie** [comment]
so therefore it should be in the root folder? because on my part, it wont work but if I also copy the directory on my home folder, it works as expected.

**Comment by ceesco53** [comment]
@cargie  same deal here.   I modified valet-linux to make a copy of /root/.valet into /home/$USER/.valet when I execute valet start.  It's an extra step but it makes it work. @jmarcher  should I submit a PR for that?  It's a little thing but stops 404 errors from happening every page request for me. (Arch user here)

**Comment by jmarcher** [comment]
@ceesco53 If you can do it would be perfect, I don't have to much time at the moment, maybe on the weekend

**Comment by ceesco53** [comment]
@jmarcher @cargie Some commands may need root access to run but valet install doesn't need to place anything into root.  I've rewritten a couple lines to install into users .valet folder.  Everything works better for me now.  I'll get a PR up shortly.  I'm on Arch but can test on Ubuntu 16.04 tomorrow or Wednesday when I'm in the office.

EDIT:  Ugh.  Failed style_ci.  I'll redo it tomorrow.

**Comment by ceesco53** [comment]
#11 Submitted.  Falls back to root install ONLY if sudo isn't detected.

**Comment by jmarcher** [comment]
Thanks!
