### ISSUE TITLE
valet install doesn't work with PHP7.1

### ISSUE THREAD

**Issue by Dylan-DPC-zz** [jmarcher/valet-linux#40]
PHP Version: PHP 7.1
OS: Ubuntu 14.04

running `valet install` gives error: 
`Unable to determine linked PHP`

**Comment by jmarcher** [comment]
Is PHP 7.1 officially supported by Ubuntu or did you pull it from a custom repo?

I can add it to the Ubuntu specific configuration file but don't know if as the official "last" version

**Comment by Dylan-DPC-zz** [comment]
No i don't see any official package yet. Most are from ppa/ondrej.

**Comment by jmarcher** [comment]
Ok, I can not add it as the latest one but can you confirm this:

I need the name of the package, the fpm service name and the fpm config file, and hope that they keep a standard

```
[
// PHP 7.1
'php-71'            => 'php7.1',
'fpm71-service'     => 'php7.1-fpm',
'fpm71-config'      => '/etc/php/7.1/php-fpm.conf',
]
```

**Comment by Dylan-DPC-zz** [comment]
You forgot the fpm directory in the path (for config). it is `/etc/php/7.1/fpm/php-fpm.conf ` (same structure for 7.0 as well).

**Comment by jmarcher** [comment]
Tagged as v2.2.1 tell me if it works

**Comment by Dylan-DPC-zz** [comment]
will give it a spin tomorrow and notify you. Thx :)

**Comment by jmarcher** [comment]
Ping @Dylan-DPC closing this, can be reopened if the problem persists
