### ISSUE TITLE
getting error when running valet install

### ISSUE THREAD

**Issue by ramsaiphp** [jmarcher/valet-linux#43]
Hi,

I have installed valet on my ubuntu 14.04 LTS with composer global require jmarcher/valet-linux.
But when i run valet install it is giving error. I am not able to run valet and giving the error.

laravel install
PHP Fatal error:  Cannot declare class Brew, because the name is already in use in /home/ramsai/.composer/vendor/jmarcher/valet-linux/cli/includes/facades.php on line 31

Please let me know if there is any fix for this issue

**Comment by jmarcher** [comment]
Hi, 

Can you please give me the output of:

```
composer global show -i
```
in order to check what is installed on the global scope

**Comment by ramsaiphp** [comment]
after running the above command i am getting like below:
You are using the deprecated option "installed". Only installed packages are shown by default now. The --all option can be used to show all packages.
container-interop/container-interop 1.1.0   Promoting the interoperability ...
cpriego/valet-ubuntu                v1.1.16 A more enjoyable local developm...
guzzlehttp/guzzle                   6.2.2   Guzzle is a PHP HTTP client lib...
guzzlehttp/promises                 v1.3.1  Guzzle promises library
guzzlehttp/psr7                     1.3.1   PSR-7 message implementation
illuminate/container                v5.4.9  The Illuminate Container package.
illuminate/contracts                v5.4.9  The Illuminate Contracts package.
jmarcher/fluent-curl-wrapper        1.0.11  A fluent PHP CURL wrapper
jmarcher/valet-linux                v2.2.1  A more enjoyable local developm...
laravel/installer                   v1.3.4  Laravel application installer.
mnapoli/silly                       1.5.1   Silly CLI micro-framework based...
nategood/httpful                    0.2.20  A Readable, Chainable, REST fri...
pdepend/pdepend                     2.5.0   Official version of pdepend to ...
php-di/invoker                      1.3.3   Generic and extensible callable...
phpmd/phpmd                         2.6.0   PHPMD is a spin-off project of ...
psr/http-message                    1.0.1   Common interface for HTTP messages
psr/log                             1.0.2   Common interface for logging li...
symfony/config                      v3.2.3  Symfony Config Component
symfony/console                     v3.2.3  Symfony Console Component
symfony/debug                       v3.2.3  Symfony Debug Component
symfony/dependency-injection        v3.2.3  Symfony DependencyInjection Com...
symfony/filesystem                  v3.2.3  Symfony Filesystem Component
symfony/polyfill-mbstring           v1.3.0  Symfony polyfill for the Mbstri...
symfony/process                     v3.2.3  Symfony Process Component
tightenco/collect                   v5.4.0  Collect - Illuminate Collection...

**Comment by jmarcher** [comment]
You need to remove the old version of: cpriego/valet-ubuntu

Because this package is a fork cpriego/valet-ubuntu, it shares almost the same structure and global functions and classes

**Comment by ramsaiphp** [comment]
Thanks it is working.
