### ISSUE TITLE
Valet only supports the Mac operating system.

### ISSUE THREAD

**Issue by ruslanashaari** [jmarcher/valet-linux#44]
This message appear when I do valet install. Please help

**Comment by jmarcher** [comment]
It seems that you have the wrong version of valet installed

Paste here the output from
composer global show

And tell me what it prints

**Comment by ruslanashaari** [comment]
Seems like I mistakenly install laravel/valet package. Already removed that, but after i do composer global require jmarcher/valet-linux, and do valet install, i received this;

PHP Fatal error:  Cannot declare class CommandLine, because the name is already in use in /home/lanesra/.config/composer/vendor/jmarcher/valet-linux/cli/includes/facades.php on line 43

Any idea?

**Comment by ruslanashaari** [comment]
Looks like the package conflict with some of the package I installed earlier. I removed that package, do clear-cache, and reinstall the package. And now the problem solved.

Thanks so much!
