### ISSUE TITLE
Te gustaría combinar esfuerzos?

### ISSUE THREAD

**Issue by cpriego** [jmarcher/valet-linux#45]
Hola @jmarcher, desde principios de febrero de este año y con ayuda de Leo Nodi se hizo un refactor muy grande del proyecto valet-ubuntu para soportar un mayor número de distros. 

Leo da soporte principalmente a Fedora (y derivados), yo a Ubuntu (y derivados) y a pesar de ya soportar oficialmente Arch Linux no contamos con alguien que lo use de manera diaria. 

Por lo que veo tu sí usas Arch como sistema principal y dado que ya tienes experiencia con este fork te extiendo una invitación para unir esfuerzos y tener un "valet linux" más robusto y con mejor soporte.

**Comment by jmarcher** [comment]
Si el otro día probé tu fork para Arch y no me funcionó, así podría dejar como discontinuada este Fork.
Yo actualmente tengo muy poco tiempo pero me encantaría poder ayudar en lo que sea para mejorar la compatibilidad con Arch.
Cuando pueda mando un PR con las cosas que vea que se necesiten para que funcione todo bien.

**Comment by jmarcher** [comment]
@cpriego Marqué este fork como discontinuado, no tengo tiempo para mantenerlo y tampoco para mergear tu versión, pero creo que está funcionando perfectamente en Arch, estuve usando tu versión por unos cuantos meses ya.

Podría ayudarte con cualquier issue o revisar PR si quieres puedes etiquetarme y con gusto cuando tenga tiempo lo miro.

Saludos
