### ISSUE TITLE
Problem with running valet install

### ISSUE THREAD

**Issue by rawzone** [jmarcher/valet-linux#6]
Hi,

I have a problem when I try to run the valet install cli command under Arch Linux i get an error about re-declaring classes in the facades. Have tried to uncomment the brew one, but then the ubuntu one just fails as the next.

```
$ valet install                                                                 
PHP Fatal error:  Cannot declare class Brew, because the name is already in use in /home/username/.composer/vendor/jmarcher/valet-linux/cli/includes/facades.php on line 28
```

Note: username replaced.

Any hints to get this installed would be very appreciated.

Thanks!

**Comment by indrakaw** [comment]
I'm having the same problem. It was my first time installing `valet-linux`.

``` sh
indrakaw@aceraspire blog $ valet install
PHP Warning:  file_get_contents(/etc/php/php-fpm.d/www.conf): failed to open stream: No such file or directory in /home/indrakaw/.config/composer/vendor/jmarcher/valet-linux/cli/Valet/Filesystem.php on line 112
PHP Warning:  file_put_contents(/etc/php/php-fpm.d/www.conf): failed to open stream: No such file or directory in /home/indrakaw/.config/composer/vendor/jmarcher/valet-linux/cli/Valet/Filesystem.php on line 125
[dnsmasq] is not installed, installing it now... 🍻

Valet installed successfully!
```

Then, I run `valet install` again.

```
indrakaw@aceraspire blog $ valet install
PHP Warning:  file_get_contents(/etc/php/php-fpm.d/www.conf): failed to open stream: No such file or directory in /home/indrakaw/.config/composer/vendor/jmarcher/valet-linux/cli/Valet/Filesystem.php on line 112
PHP Warning:  file_put_contents(/etc/php/php-fpm.d/www.conf): failed to open stream: No such file or directory in /home/indrakaw/.config/composer/vendor/jmarcher/valet-linux/cli/Valet/Filesystem.php on line 125

Valet installed successfully!
```

To next step:
1. Start `valet park`
2. Then I open `http://blog.dev`
3. It shows Apache directory instead.

OS: **Ubuntu 16.04 LTS**
Architect: **64-bit**

**Comment by adriaanzon** [comment]
@indrakaw That's because apache already listens on port 80. I don't think you can use Apache and Valet simultaneously.

**Comment by rawzone** [comment]
However this is the problem I am having. I have no webserver either install, running or listing on any ports... But I guess this fork is to Ubuntu / Debian focused to be working outside that.
